services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - ${ENV_FILE:-env/dev.env}  # ENV_FILE 환경변수가 없으면 기본값으로 dev.env 사용
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
